spring:
  application:
    name: The Coffee Shop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/the_coffee_shop}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:1234567}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  jwt:
    secret: ${JWT_SECRET:e4dccfd4c9322d015665dc1b4081c58b18eb327b82fff7d6c8de9c60840e8a9b}
    expiration: PT30M